# Generated by Django 5.2 on 2025-04-28 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountClass',
            fields=[
                ('number', models.PositiveSmallIntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Classe de compte',
                'verbose_name_plural': 'Classes de comptes',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='AccountType',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(choices=[('actif', 'Actif'), ('passif', 'passif'), ('charge', 'Dépense'), ('produit', 'Revenu'), ('capitaux_propres', 'Capitaux propres')], max_length=50)),
            ],
            options={
                'verbose_name': 'Type de compte',
                'verbose_name_plural': 'Types de comptes',
            },
        ),
        migrations.CreateModel(
            name='AccountGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField()),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('account_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='accounts.accountclass')),
            ],
            options={
                'verbose_name': 'Groupe de comptes',
                'verbose_name_plural': 'Groupes de comptes',
                'ordering': ['number'],
                'unique_together': {('account_class', 'number')},
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='accounts.accountgroup')),
                ('account_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.accounttype')),
            ],
            options={
                'verbose_name': 'Compte',
                'verbose_name_plural': 'Comptes',
                'ordering': ['number'],
                'unique_together': {('account_group', 'number')},
            },
        ),
    ]
