# Generated by Django 5.2 on 2025-04-29 05:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountclass',
            name='description',
            field=models.TextField(blank=True, help_text="Description optionnelle détaillant la nature et l'utilisation de cette classe de compte.", verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='accountclass',
            name='name',
            field=models.CharField(help_text='Nom de la classe de comptable.', max_length=100, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='accountclass',
            name='number',
            field=models.PositiveSmallIntegerField(help_text='Entrez un chiffre entre 1 et 8 conformément au plan comptable.', primary_key=True, serialize=False, unique=True, validators=[django.core.validators.MinValueValidator(1, message='Le numéro de classe doit être au minimum 1.'), django.core.validators.MaxValueValidator(8, message='Le numéro de classe doit être au maximum 8.')], verbose_name='Numéro'),
        ),
    ]
