# Generated by Django 5.2 on 2025-04-29 05:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_accountclass_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountclass',
            name='actif',
            field=models.BooleanField(default=True, help_text='Indique si cette classe est active dans le plan comptable', verbose_name='Active'),
        ),
        migrations.AddField(
            model_name='accountclass',
            name='date_creation',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de création'),
        ),
        migrations.AddField(
            model_name='accountclass',
            name='position_bilan',
            field=models.CharField(choices=[('Actif', 'Actif'), ('Passif', 'Passif'), ('Charges', 'Charges'), ('Produits', 'Produits')], default='Actif', help_text="Indique si la classe est dans l'Actif, Passif, Charges ou Produits", max_length=20, verbose_name='Position dans le bilan'),
        ),
        migrations.AlterField(
            model_name='accountclass',
            name='description',
            field=models.TextField(blank=True, editable=False, help_text="Description optionnelle détaillant la nature et l'utilisation de cette classe de compte.", verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='accountclass',
            name='name',
            field=models.CharField(editable=False, help_text='Nom de la classe de comptable.', max_length=100, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='accountclass',
            name='number',
            field=models.PositiveSmallIntegerField(help_text='Entrez un chiffre entre 1 et 8 conformément au plan comptable OHADA.', primary_key=True, serialize=False, unique=True, validators=[django.core.validators.MinValueValidator(1, message='Le numéro de classe doit être au minimum 1.'), django.core.validators.MaxValueValidator(8, message='Le numéro de classe doit être au maximum 8.')], verbose_name='Numéro'),
        ),
    ]
