# Generated by Django 5.2 on 2025-04-29 07:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_accountclass_actif_accountclass_date_creation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountclass',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 4, 29, 7, 42, 15, 915093, tzinfo=datetime.timezone.utc), verbose_name='Date de création'),
            preserve_default=False,
        ),
    ]
