# Generated by Django 5.2 on 2025-04-29 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_accountgroup_actif_accountgroup_date_creation_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accounttype',
            options={'ordering': ['code'], 'verbose_name': 'Type de compte', 'verbose_name_plural': 'Types de comptes'},
        ),
        migrations.AlterField(
            model_name='accounttype',
            name='code',
            field=models.CharField(choices=[('A', 'Actif'), ('P', 'Passif'), ('C', 'Charge'), ('P', 'Produit'), ('CP', 'Capitaux propres')], help_text='Code unique du type de compte (A, P, C, P, CP)', max_length=20, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='accounttype',
            name='name',
            field=models.CharField(help_text='Nom descriptif du type de compte', max_length=50),
        ),
    ]
