# Generated by Django 5.2 on 2025-04-29 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_accounttype_options_alter_accounttype_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounttype',
            name='code',
            field=models.CharField(choices=[('AC', 'AC'), ('PA', 'PA'), ('CH', 'CH'), ('PR', 'PR'), ('CP', 'CP')], help_text='Code unique du type de compte (AC, PA, CH, PR, CP)', max_length=5, primary_key=True, serialize=False, unique=True),
        ),
    ]
