# Generated by Django 5.2 on 2025-04-29 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_accounttype_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounttype',
            name='description',
            field=models.TextField(blank=True, editable=False, help_text='Description détaillée du groupe de comptes (générée automatiquement).', verbose_name='Description'),
        ),
    ]
