# Generated by Django 5.2 on 2025-04-29 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_accounttype_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounttype',
            name='description',
            field=models.CharField(blank=True, editable=False, help_text='Description détaillée du type de compte (générée automatiquement)', max_length=255, verbose_name='Description'),
        ),
    ]
